### ISSUE TITLE
[要望]ダークモードを実装してほしい

### ISSUE THREAD

**Issue by daima3629** [yhira/chirashi#1]
- 概要
黒、もしくはそれに近い灰色などを基調としたテーマに変更できる機能を用意してほしい。
イメージはこちらのWindows11のメモ帳のような感じです。
![image](https://pc.watch.impress.co.jp/img/pcw/docs/1372/495/1_l.jpg)

こちらがPRを出せれば一番良いのですが、私がDelphiに関しての知識が一切ないためissueでお願いという形になってしまいます。
お手好きの際に実装していただければ幸いです。よろしくお願いします。

**Comment by yhira** [comment]
ダークモードに対応させてみました。
https://nelog.jp/chirashi
ダークテーマはいろいろ探しましたが、これ以上良いものはありませんでした。
<img width="543" alt="2022-10-31_02h53_18" src="https://user-images.githubusercontent.com/1787429/198894532-b5c68cc0-b910-47ad-896e-c349ba42af90.png">
あとは全部真っ黒とかしかなかったです。

**Comment by yhira** [comment]
ちなみに真っ黒だとこんな感じです。
<img width="543" alt="2022-10-31_03h24_58" src="https://user-images.githubusercontent.com/1787429/198895130-452612b3-ee7e-4dbc-8e62-07dfbf9d9d37.png">

**Comment by daima3629** [comment]
ありがとうございます！まさに私が求めていたものです！
早速使わせていただきます、ご対応ありがとうございました。

**Comment by yhira** [comment]
ご確認いただきありがとうございます。
